### ISSUE TITLE
Updating metrics - db failures

### ISSUE THREAD

**Issue by romanchyla** [adsabs/ADSMasterPipeline#17]
seems like the connection (or perhaps the engine?) needs to be invalidated; but those errors are hard to pinpoint:

```2017-10-31_18:51:07.95329 [2017-10-31 18:51:07,952: ERROR/ForkPoolWorker-2] Task adsmp.tasks.task_index_records[4f81814b-8e0e-4b91-a6c6-796c1617a848] raised unexpected: StatementError("(sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back",)
2017-10-31_18:51:07.95330 Traceback (most recent call last):
2017-10-31_18:51:07.95330   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
2017-10-31_18:51:07.95330     R = retval = fun(*args, **kwargs)
2017-10-31_18:51:07.95331   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
2017-10-31_18:51:07.95331     return self.run(*args, **kwargs)
2017-10-31_18:51:07.95331   File "/app/adsmp/tasks.py", line 182, in task_index_records
2017-10-31_18:51:07.95331     app.update_metrics_db(batch_insert, batch_update)
2017-10-31_18:51:07.95332   File "/app/adsmp/app.py", line 298, in update_metrics_db
2017-10-31_18:51:07.95332     r = self._metrics_conn.execute(self._metrics_table_update, batch_update)
2017-10-31_18:51:07.95332   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
2017-10-31_18:51:07.95332     return meth(self, multiparams, params)
2017-10-31_18:51:07.95333   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
2017-10-31_18:51:07.95333     return connection._execute_clauseelement(self, multiparams, params)
2017-10-31_18:51:07.95334   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2017-10-31_18:51:07.95334     compiled_sql, distilled_params
2017-10-31_18:51:07.95334   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1121, in _execute_context
2017-10-31_18:51:07.95335     None, None)
2017-10-31_18:51:07.95335   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
2017-10-31_18:51:07.95335     exc_info
2017-10-31_18:51:07.95335   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2017-10-31_18:51:07.95336     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2017-10-31_18:51:07.95336   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1114, in _execute_context
2017-10-31_18:51:07.95336     conn = self._revalidate_connection()
2017-10-31_18:51:07.95336   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 424, in _revalidate_connection
2017-10-31_18:51:07.95337     "Can't reconnect until invalid "
2017-10-31_18:51:07.95337 StatementError: (sqlalchemy.exc.InvalidRequestError) Can't reconnect until invalid transaction is rolled back [SQL: u'UPDATE metrics SET bibcode=%(bibcode)s, an_citations=%(an_citations)s, an_refereed_citations=%(an_refereed_citations)s, author_num=%(author_num)s, citations=%(citations)s, citation_num=%(citation_num)s, downloads=%(downloads)s, reads=%(reads)s, refereed=%(refereed)s, refereed_citations=%(refereed_citations)s, refereed_citation_num=%(refereed_citation_num)s, reference_num=%(reference_num)s, rn_citations=%(rn_citations)s, rn_citation_data=%(rn_citation_data)s, modtime=%(modtime)s WHERE metrics.bibcode = %(bibcode)s'] [parameters: [{u'modtime': u'2017-10-20T23:16:51Z', u'refereed': True, u'rn_citations_hist': {u'2017': 0.06528981029987335}, u'citations': [u'2017PreR..298...56D', u'2017PreR..300..121O'], u'downloads': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], u'rn_citations': 0.03897399827837944, u'citation_num': 2, u'an_citations': 1.0, u'refereed_citation_num': 2, u'reads': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], u'bibcode': u'2016PreR..286....1S', u'refereed_citations': [u'2017PreR..300..121O', u'2017PreR..298...56D'], u'author_num': 8, u'reference_num': 33, u'an_refereed_citations': 1.0, u'rn_citation_data': [{u'cityear': 2017, u'pubyear': 2016, u'auth_norm': 0.125, u'bibcode': u'2017PreR..300..121O', u'ref_norm': 0.02631578966975212}, {u'cityear': 2017, u'pubyear': 2016, u'auth_norm': 0.125, u'bibcode': u'2017PreR..298...56D', u'ref_norm': 0.012658228166401386}]^C
```

**Comment by romanchyla** [comment]
fix pushed to master; now we are getting these:

```2017-10-31_19:09:47.42151 trace=Traceback (most recent call last):
2017-10-31_19:09:47.42151   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
2017-10-31_19:09:47.42151     R = retval = fun(*args, **kwargs)
2017-10-31_19:09:47.42154   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
2017-10-31_19:09:47.42155     return self.run(*args, **kwargs)
2017-10-31_19:09:47.42155   File "/app/adsmp/tasks.py", line 182, in task_index_records
2017-10-31_19:09:47.42156     app.update_metrics_db(batch_insert, batch_update)
2017-10-31_19:09:47.42156   File "/app/adsmp/app.py", line 318, in update_metrics_db
2017-10-31_19:09:47.42157     raise e
2017-10-31_19:09:47.42157 OperationalError: (psycopg2.OperationalError) SSL SYSCALL error: EOF detected```

**Comment by romanchyla** [comment]
this was fixed (problem of shared connections)
