### ISSUE TITLE
Delete metrics error

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/ADSMasterPipeline#66]
Perhaps deleting a metrics record always fails:
```
Task=be2d44e1-7e6b-46b4-9765-31c076f8d2c6 failed.
args=[<adsmsg.denormalized_record.DenormalizedRecord object at 0x7f9589dcabd0>]
kwargs={}
trace=Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/adsmp/tasks.py", line 42, in task_update_record
    task_delete_documents(msg.bibcode)
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 630, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 380, in __call__
    return self.run(*args, **kwargs)
  File "/app/adsmp/tasks.py", line 221, in task_delete_documents
    if app.metrics_delete_by_bibcode(bibcode):
  File "/app/adsmp/app.py", line 484, in metrics_delete_by_bibcode
    r = session.query(MetricsRecord).filter_by(bibcode=bibcode).first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1330, in query
    return self._query_cls(entities, self, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 139, in __init__
    self._set_entities(entities)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 148, in _set_entities
    entity_wrapper(self, ent)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3947, in __init__
    "expected - got '%r'" % (column, )
InvalidRequestError: SQL expression, column, or mapped entity expected - got '<class 'adsmsg.metrics_record.MetricsRecord'>'
```

**Comment by spacemansteve** [comment]
The code to [delete metrics](https://github.com/adsabs/ADSMasterPipeline/blob/master/adsmp/app.py#L506) data for a bibcode is passing the Protobuf record definition to SQLalchemy, not the SQLalchemy model.  MetricsRecord should be MetricsModel.
